# docker-compose.yml

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=wnba_db
    # --- The Healthcheck Section ---
    healthcheck:   # This tells Docker how to check if the PostgreSQL server is actually ready.
      test: ["CMD-SHELL", "pg_isready -U admin -d wnba_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy # Tells the backend to wait for the db to be ready

  backend-prod-test:
    build:
      context: ./backend
      # This is the key difference: it builds the final production stage
      target: production
    # We don't mount volumes because a production image should be self-contained
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: 
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: