# .github/workflows/ci.yml
name: Full Stack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- First Job: Backend Tests ---
  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        # We run commands from the project root now
        working-directory: .

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install flake8 pytest

    - name: Lint with Flake8
      run: flake8 backend/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Backend Tests with Pytest
      run: pytest backend/

  # --- Second Job: Frontend Tests (runs in parallel to backend) ---
  frontend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm' # Speeds up builds by caching dependencies
        cache-dependency-path: frontend/package-lock.json

    - name: Install Frontend Dependencies
      # npm ci is faster and more reliable for CI than npm install
      run: npm ci

    - name: Run Frontend Tests
      # The flags are important for running in a non-interactive CI environment
      run: npm test -- --watchAll=false